---

name: Packer Validation and Building Artifact.

on:
  push:
    branches: [main]
    
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # # fix backwards incompatibilities in template
      # - name: Fix Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ubuntu.packer.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ubuntu.packer.pkr.hcl
          # working_directory: infrastructure/packer
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_username: "ubuntu"

      # additional steps to process artifacts
